contact_links:
  - name: Discord Les Moddeurs Français
    url: https://discord.lesmoddeursfrancais.fr/
    about: Rejoignez notre Discord si vous avez des questions à propos du projet de la documentation